version: '3.9'

services:
  php:
    image: wodby/php:latest
    volumes:
      - './html:/var/www/html'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - "88:80"
    links:
      - php
    volumes:
      - './html:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  mariadb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
     
    ports:
      - "1088:80"
    depends_on:
      - mariadb

volumes:
  mysqldata:
